# -----------------------------------
# Author: Nicola Biancolini
#         nicola.biancolini@reactconsulting.it
#
# Company: React Consulting S.r.l.
#          http://reactconsulting.it
#
# Summary: Docker base image for windows platform company implementations.
#
# Container informations
#   - Name: reactconsulting/windowsservercore
#   - Tag: ltsc2016
#
# Example build: docker build -t "reactconsulting/windowsservercore:ltsc2016" ./
# -----------------------------------

# Set start image
FROM microsoft/windowsservercore:ltsc2016

# Set image labes
LABEL mantainer="Nicola Biancolini <nicola.biancolini@reactconsulting.it>"

