# -----------------------------------
# Author: Nicola Biancolini
#         nicola.biancolini@reactconsulting.it
#
# Company: React Consulting S.r.l.
#          http://reactconsulting.it
#
# Summary: Docker base image for windows and java platform company implementations.
#
# Container informations
#   - Name: reactconsulting/windowsservercore-openjdk
#   - Tag: 10
#
# Example build: docker build -t "reactconsulting/windowsservercore-openjdk:10" ./
# -----------------------------------

# Set start image
FROM openjdk:10-windowsservercore-ltsc2016

# Set image labes
LABEL mantainer="Nicola Biancolini <nicola.biancolini@reactconsulting.it>"