# -----------------------------------
# Author: Nicola Biancolini
#         nicola.biancolini@reactconsulting.it
#
# Company: React Consulting S.r.l.
#          http://reactconsulting.it
#
# Summary: Docker base image for windows platform company implementations.
#
# Container informations
#   - Name: reactconsulting/windowsservercore
#   - Tag: latest
#
# Example build: docker build -t "reactconsulting/windowsservercore:latest" ./
# -----------------------------------

# Set start image
FROM microsoft/windowsservercore:latest

# Set image labes
LABEL maintainer="Nicola Biancolini <nicola.biancolini@reactconsulting.it>"